name: hnet

channels: 
    - pytorch 
    - nvidia 
    - pyg
    - conda-forge
    - defaults 

dependencies:
    - python
    - matplotlib
    - pyg
    - pytorch::pytorch
    - pytorch::pytorch-cuda
    - torchvision
    - seaborn
    - scikit-learn
    - scipy
    - pip
    - pip:
        - ipykernel
