name: hnet

channels: 
    - pytorch 
    - nvidia 
    - pyg
    - conda-forge
    - mcs07
    - defaults 

dependencies:
    - python=3.10
    - matplotlib
    - pyg
    - pytorch
    - pytorch-cuda
    - seaborn
    - scikit-learn
    - scipy
    - pip
    - pip:
        - ipykernel
        - adjustText
        - torch-sparse 
        - torch-scatter
        - torch-cluster
